Add bin full alert to HaclCodes
bm1549/frigidaire pull request #7
Opened 2021-09-06 16:51 UTC by AdamCLarsen

2021-09-14 16:19 UTC, bm1549 requested changes

2021-09-14 16:19 UTC, bm1549 commented on setup.py
> +    version='0.15',
Can you rebase this on main?

2021-09-14 16:54 UTC, AdamCLarsen commented on setup.py
> +    version='0.15',
Done.

2021-09-14 18:35 UTC, bm1549 approved these changes

2021-09-14 18:35 UTC, merged

2021-09-14 18:36 UTC, bm1549 commented
I can't tag the release for the next few days because I'm away and can't do it on mobile but I'll do it when I get back

2021-09-14 19:02 UTC, gazpachoking commented
> I can't tag the release for the next few days because I'm away and can't do it on mobile but I'll do it when I get back

I can take care of this one too if you want.

2021-09-14 21:07 UTC, bm1549 commented
@gazpachoking yes please 🙏

2021-09-15 01:54 UTC, gazpachoking commented
0.16 is good to go!